language: c
compiler: gcc
before_script: 
  - ffmpeg -version
  - autoreconf -fiv
script: ./configure && make

matrix:
  include:
    - name: ubuntu 12.04
      addons:
        apt:
          packages:
            - libavformat-dev
            - libavcodec-dev
            - libav-tools
            - libavutil-dev
            - libswscale-dev
            - ffmpeg
            - libjpeg8-dev
            - libv4l-dev
            - libzip-dev
    - name: ubuntu 12.04 ffmpeg 3.0.1
      before_install:
        - sudo add-apt-repository ppa:mc3man/trusty-media
        - sudo apt-get -y update
      addons:
        apt:
          pacakges:
            - libavformat-dev
            - libavcodec-dev
            - libav-tools
            - libavutil-dev
            - libswscale-dev
            - ffmpeg
            - libjpeg8-dev
            - libv4l-dev
            - libzip-dev
