language: c
compiler: gcc
before_install:
  - sudo apt-add-repository -y ppa:travis-ci/sqlite3
  - sudo apt-get -y update
  - sudo apt-get -y install libsqlite3-dev=3.7.15.1-1~travis1
before_script: autoreconf -i
addons:
  apt:
    packages:
      - build-essential
      - pkg-config
      - libavcodec-dev
      - libavformat-dev

script: ./configure --with-sqlite && make && make test
