language: c
before_script: autoreconf -fiv
script: ./configure && make


matrix:
  include:
    - compiler: gcc
      addons:
        apt:
          packages:
            - libavformat-dev
            - libavcodec-dev
            - libav-tools
            - libavutil-dev
            - libswscale-dev
            - ffmpeg
            - libjpeg8-dev
            - libv4l-dev
            - libzip-dev
